const APP_KEY='pastelBroskiUser';
const configReady = typeof firebaseConfig === 'object' && firebaseConfig.databaseURL;
let db=null; try { if(configReady){ firebase.initializeApp(firebaseConfig); db=firebase.database(); } } catch(e){ console.error(e); }

const $=id=>document.getElementById(id);
const state={user:localStorage.getItem(APP_KEY)||'', mode:'login', events:{}, users:{}, currentDate:new Date(), filter:'all', filterUser:'', editingId:null, theme:localStorage.getItem('pastelTheme')||'maroon', unsubs:[]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cleanUser=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,24);
const pad=n=>String(n).padStart(2,'0');
const dateStr=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parseDate=s=>{const [y,m,d]=s.split('-').map(Number); return new Date(y,m-1,d)};
const monthLabel=d=>d.toLocaleDateString('en-US',{month:'long',year:'numeric'});
const sameDay=(a,b)=>dateStr(a)===dateStr(b);

function toast(msg){ const n=$('toast'); n.textContent=msg; n.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>n.classList.remove('show'),2600); }
function setTheme(theme){ state.theme=theme; document.documentElement.dataset.theme=theme; localStorage.setItem('pastelTheme',theme); }
setTheme(state.theme);
$('themeBtn').onclick=()=> $('themePopover').classList.toggle('hidden');
document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{setTheme(b.dataset.theme);$('themePopover').classList.add('hidden');});

function setAuthMode(mode){ state.mode=mode; $('loginTab').classList.toggle('active',mode==='login'); $('signupTab').classList.toggle('active',mode==='signup'); $('authSubmit').textContent=mode==='login'?'Sign in':'Create account'; }
$('loginTab').onclick=()=>setAuthMode('login'); $('signupTab').onclick=()=>setAuthMode('signup');
$('authForm').onsubmit=async e=>{e.preventDefault(); const u=cleanUser($('usernameInput').value), p=$('passwordInput').value.trim(); if(!u||!p) return toast('Username and password are required.'); if(!db) return toast('Firebase database is not connected.'); try { const ref=db.ref('users/'+u); const snap=await ref.once('value'); if(state.mode==='signup'){ if(snap.exists()) return toast('That username already exists.'); await ref.set({password:p, createdAt:Date.now()}); toast('Account created. Welcome!'); } else { if(!snap.exists()) return toast('User not found. Create an account first.'); const data=snap.val()||{}; if(data.password!==p) return toast('Incorrect password.'); } loginAs(u); } catch(err){ console.error(err); toast('Could not connect to Firebase.'); }};

function loginAs(u){ state.user=u; localStorage.setItem(APP_KEY,u); $('loginView').classList.add('hidden'); $('appView').classList.remove('hidden'); $('profileTag').textContent='@'+u; $('avatar').textContent=u[0].toUpperCase(); $('greeting').textContent='Hi, '+u+'!'; $('passwordInput').value=''; startListeners(); resetForm(); renderAll(); }
$('logoutBtn').onclick=()=>{ stopListeners(); localStorage.removeItem(APP_KEY); state.user=''; $('appView').classList.add('hidden'); $('loginView').classList.remove('hidden'); };

function startListeners(){ stopListeners(); if(!db) return; const usersRef=db.ref('users'); const evRef=db.ref('shared_events_v3'); const ucb=usersRef.on('value',s=>{state.users=s.val()||{}; renderParticipants(); renderFilters();}); const ecb=evRef.on('value',s=>{state.events=s.val()||{}; renderAll();}); state.unsubs=[()=>usersRef.off('value',ucb),()=>evRef.off('value',ecb)]; }
function stopListeners(){state.unsubs.forEach(fn=>fn());state.unsubs=[];}

function monthEvents(){const ym=`${state.currentDate.getFullYear()}-${pad(state.currentDate.getMonth()+1)}`; return Object.entries(state.events).filter(([,e])=>String(e.startDate||'').startsWith(ym)||String(e.endDate||'').startsWith(ym));}
function eventAppliesToDate(e,d){const s=parseDate(e.startDate), en=parseDate(e.endDate||e.startDate); const x=new Date(d.getFullYear(),d.getMonth(),d.getDate()); return x>=s&&x<=en;}
function associated(e){const ps=String(e.participant||'').split(',').map(x=>x.trim()).filter(Boolean); return e.owner===state.user||ps.includes(state.user);}
function renderCalendar(){ const y=state.currentDate.getFullYear(), m=state.currentDate.getMonth(); $('monthTitle').textContent=monthLabel(state.currentDate); const first=new Date(y,m,1), start=new Date(y,m,1-first.getDay()); const html=[]; for(let i=0;i<42;i++){ const d=new Date(start); d.setDate(start.getDate()+i); const other=d.getMonth()!==m; const today=sameDay(d,new Date()); const selected=sameDay(d,state.selectedDate||new Date()); const evs=Object.values(state.events).filter(e=>eventAppliesToDate(e,d)&&associated(e)).slice(0,3); html.push(`<button class="day-cell ${other?'other ':''}${today?'today ':''}${selected?'selected':''}" data-date="${dateStr(d)}"><span class="day-num">${d.getDate()}</span><span class="day-dots">${evs.map(e=>`<i title="${esc(e.title)}"></i>`).join('')}</span></button>`); } $('calendarGrid').innerHTML=html.join(''); document.querySelectorAll('.day-cell').forEach(b=>b.onclick=()=>{state.selectedDate=parseDate(b.dataset.date); renderAll();}); }

function renderParticipants(){ const users=Object.keys(state.users).filter(u=>u!==state.user).sort(); $('participantList').innerHTML=users.length?users.map(u=>`<label class="check-pill"><input type="checkbox" value="${esc(u)}"><span>${esc(u)}</span></label>`).join(''):'<div class="empty">No other users yet.</div>'; }
function selectedParticipants(){ return [...document.querySelectorAll('#participantList input:checked')].map(x=>x.value); }
$('selectAllBtn').onclick=()=>{const c=[...document.querySelectorAll('#participantList input')]; const make=c.some(x=>!x.checked); c.forEach(x=>x.checked=make); };
function renderFilters(){ const names=Object.keys(state.users).filter(u=>u!==state.user).sort(); $('filterUserSelect').innerHTML='<option value="">Select a user</option>'+names.map(u=>`<option value="${esc(u)}">@${esc(u)}</option>`).join(''); $('filterUserSelect').value=state.filterUser; $('filterUserSelect').classList.toggle('hidden',state.filter!=='specific'); }
document.querySelectorAll('.filter-pill').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter; document.querySelectorAll('.filter-pill').forEach(x=>x.classList.toggle('active',x===b)); if(state.filter!=='specific') state.filterUser=''; renderFilters(); renderEventLists();});
$('filterUserSelect').onchange=e=>{state.filterUser=e.target.value; renderEventLists();};

function passesFilter(e){const ps=String(e.participant||'').split(',').map(x=>x.trim()); if(state.filter==='all') return true; if(state.filter==='me') return e.owner===state.user||ps.includes(state.user); if(state.filter==='specific') return !!state.filterUser&&(e.owner===state.filterUser||ps.includes(state.filterUser)); return true;}
function eventHtml(id,e,compact=false){const ps=String(e.participant||'').split(',').map(x=>x.trim()).filter(Boolean); const canEdit=e.owner===state.user||ps.includes(state.user); const time=e.time?`<span class="time-badge">${esc(e.time)}</span>`:''; return `<li class="event-item cat-${esc(e.category||'personal')}"><div class="event-main"><div><strong>${esc(e.title)}</strong><span class="owner">by @${esc(e.owner||'unknown')}</span></div><div class="event-meta">${time}${e.startDate}${e.endDate&&e.endDate!==e.startDate?' → '+e.endDate:''}${ps.length?` · with @${ps.map(esc).join(', @')}`:''}</div>${e.notes&&!compact?`<div class="notes">${esc(e.notes)}</div>`:''}</div>${canEdit&&!compact?`<div class="event-actions"><button data-edit="${id}">✏️</button><button data-delete="${id}">×</button></div>`:''}</li>`; }
function renderEventLists(){ const d=state.selectedDate||new Date(); $('selectedDateLabel').textContent=d.toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'}); const day=Object.entries(state.events).filter(([,e])=>eventAppliesToDate(e,d)&&associated(e)&&passesFilter(e)).sort((a,b)=>(a[1].time||'99:99').localeCompare(b[1].time||'99:99')); $('eventList').innerHTML=day.length?day.map(([id,e])=>eventHtml(id,e)).join(''):'<li class="empty">No plans for this date.</li>'; bindEventActions(); const q=$('searchInput').value.trim().toLowerCase(); const incoming=Object.entries(state.events).filter(([,e])=>associated(e)).filter(([,e])=>{const text=`${e.title} ${e.owner} ${e.participant||''}`.toLowerCase(); return !q||text.includes(q);}).sort((a,b)=>String(a[1].startDate).localeCompare(String(b[1].startDate))).slice(0,15); $('incomingList').innerHTML=incoming.length?incoming.map(([id,e])=>eventHtml(id,e,true)).join(''):'<li class="empty">No matching incoming plans.</li>'; bindEventActions(); }
function bindEventActions(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit)); document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeEvent(b.dataset.delete));}

function renderMetrics(){ const month=monthEvents().filter(([,e])=>e.owner===state.user||String(e.participant||'').split(',').includes(state.user)); $('metricMyPlans').textContent=month.length; const pct=Math.min(month.length*12.5,100); $('hypeBar').style.width=pct+'%'; $('hypeLabel').textContent=month.length>=8?'Busy month 🔥':month.length>=4?'Good month ✨':'Chill month 🧊'; }
function renderCountdown(){ const now=Date.now(); let next=null; Object.values(state.events).forEach(e=>{ if(!associated(e)) return; const dt=new Date(`${e.startDate}T${e.time||'00:00'}`).getTime(); if(dt>now&&(!next||dt<next.dt)) next={e,dt}; }); if(!next){$('countdownTitle').textContent='No upcoming plan';$('countdownTimer').textContent='00d 00h 00m 00s';return;} $('countdownTitle').textContent=next.e.title; const diff=Math.max(0,next.dt-Date.now()); const s=Math.floor(diff/1000), d=Math.floor(s/86400), h=Math.floor((s%86400)/3600), m=Math.floor((s%3600)/60), ss=s%60; $('countdownTimer').textContent=`${pad(d)}d ${pad(h)}h ${pad(m)}m ${pad(ss)}s`; }
setInterval(renderCountdown,1000);

function renderAll(){renderCalendar();renderEventLists();renderMetrics();renderCountdown();} $('prevMonth').onclick=()=>{state.currentDate.setMonth(state.currentDate.getMonth()-1);renderCalendar();renderMetrics();}; $('nextMonth').onclick=()=>{state.currentDate.setMonth(state.currentDate.getMonth()+1);renderCalendar();renderMetrics();}; $('todayBtn').onclick=()=>{state.currentDate=new Date();state.selectedDate=new Date();renderAll();}; $('navToday').onclick=()=>{state.currentDate=new Date();state.selectedDate=new Date();renderAll();}; $('fab').onclick=()=>openNew(); $('addEventBtn').onclick=()=>openNew(); $('navAdd').onclick=()=>openNew(); $('searchInput').oninput=renderEventLists;

function resetForm(){ $('eventId').value='';$('eventTitle').value='';$('startDate').value=dateStr(state.selectedDate||new Date());$('endDate').value=dateStr(state.selectedDate||new Date());$('eventTime').value='';$('eventCategory').value='personal';$('eventNotes').value='';$('deleteBtn').classList.add('hidden');$('modalTitle').textContent='Add event';$('modalEyebrow').textContent='NEW EVENT';document.querySelectorAll('#participantList input').forEach(x=>x.checked=false);state.editingId=null;}
function openNew(){resetForm();$('eventModal').classList.remove('hidden');}
function openEdit(id){const e=state.events[id];if(!e)return; resetForm(); state.editingId=id; $('eventId').value=id;$('eventTitle').value=e.title||'';$('startDate').value=e.startDate;$('endDate').value=e.endDate||e.startDate;$('eventTime').value=e.time||'';$('eventCategory').value=e.category||'personal';$('eventNotes').value=e.notes||''; const ps=String(e.participant||'').split(',').map(x=>x.trim()); document.querySelectorAll('#participantList input').forEach(x=>x.checked=ps.includes(x.value)); $('deleteBtn').classList.toggle('hidden',e.owner!==state.user); $('modalTitle').textContent='Edit event';$('modalEyebrow').textContent='EDIT EVENT';$('eventModal').classList.remove('hidden');}
function closeModal(){$('eventModal').classList.add('hidden');}
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal);
$('eventForm').onsubmit=async e=>{e.preventDefault(); if(!db||!state.user)return; const title=$('eventTitle').value.trim(), sd=$('startDate').value, ed=$('endDate').value; if(!title||!sd||!ed)return toast('Title and dates are required.'); if(ed<sd)return toast('End date cannot be before start date.'); const payload={title,startDate:sd,endDate:ed,time:$('eventTime').value,category:$('eventCategory').value,notes:$('eventNotes').value.trim(),participant:selectedParticipants().join(', '),owner:state.user,updatedAt:Date.now()}; try{ if(state.editingId){ await db.ref('shared_events_v3/'+state.editingId).update(payload); toast('Event updated.'); } else { payload.createdAt=Date.now(); await db.ref('shared_events_v3').push(payload); toast('Event added and synced.'); } closeModal(); resetForm(); }catch(err){console.error(err);toast('Could not save event.');}};
$('deleteBtn').onclick=()=>{if(state.editingId)removeEvent(state.editingId);};
async function removeEvent(id){const e=state.events[id]; if(!e)return; if(e.owner!==state.user){return toast('Only the event owner can delete it.');} if(!confirm('Delete this event?'))return; try{await db.ref('shared_events_v3/'+id).remove();toast('Event deleted.');closeModal();}catch(err){toast('Could not delete event.');}}

state.selectedDate=new Date(); if(state.user&&db){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('profileTag').textContent='@'+state.user;$('avatar').textContent=state.user[0].toUpperCase();$('greeting').textContent='Hi, '+state.user+'!';startListeners();} else {setAuthMode('login');}
